<?php

namespace App\Policies;

use App\Models\ScoreRisque;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\Agent;
use App\Models\Admin;

class ScoreRisquePolicy
{
    public function viewAny(Authenticatable $user): bool
    {
        return true;
    }

    public function view(Authenticatable $user, ScoreRisque $score): bool
    {
        if ($user instanceof Admin) {
            return true;
        }

        if ($user instanceof Agent) {
            return $user->centre_sante_id === $score->enfant->centre_sante_id;
        }

        return false;
    }

    public function create(Authenticatable $user): bool
    {
        return false; // Automatically generated by VaccinationService
    }

    public function update(Authenticatable $user, ScoreRisque $score): bool
    {
        return false; // Automatically updated by VaccinationService
    }

    public function delete(Authenticatable $user, ScoreRisque $score): bool
    {
        return $user instanceof Admin;
    }
}
